name: myapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_map: ^8.2.1
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  http: ^1.2.0
  google_fonts: ^6.2.1
  bloc: ^9.0.0
  provider: ^6.1.2
  google_maps_flutter: ^2.13.1
  flutter_dotenv: ^6.0.0
  introduction_screen: ^4.0.0
  shared_preferences: ^2.5.3
  firebase_core: ^3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
